---
apiVersion: v1
kind: Template
metadata:
  name: idp-configs-api
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: idp-configs-api
  spec:
    # The name of the ClowdEnvironment providing the services
    envName: ${ENV_NAME}
    # The bulk of your App. This is where your running apps will live
    deployments:
    - name: service
      web: true
      # Give details about your running pod
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:        
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: ENABLE_CLOUDWATCH_LOGGING
          value: ${ENABLE_CLOUDWATCH_LOGGING}
        resources:
          limits:
            cpu: ${{CPU_LIMIT}}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 500m
            memory: 512Mi    

parameters:
  - name: IMAGE
    value: quay.io/vnambiar/idp-configs-api
  - name: IMAGE_TAG
    value: latest
  - name: ENV_NAME
    required: false
  - description: Determines Clowder deployment
    name: CLOWDER_ENABLED
    value: "True"
  - description: Determines if Cloud Watch logging is enabled
    name: ENABLE_CLOUDWATCH_LOGGING
    value: "False"